#page title
page_title                                : Cool Front End Templates           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 785385147                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : id                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/id/app/lazada-2-2-festival/id785385147?l=id                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.lazada.android                                          # Enter Google Play Store URL.
presskit_download_link                    : https://www.lazada.co.id/hedod/    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Hedod | Lazada ID                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : GRATIS                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Berbelanja di Aplikasi memiliki banyak keuntungan. Banyak Voucher. Produk Eksklusif di App.
                                            Rekomendasi Hanya Untuk Anda. Dapatkan Promo Pertama. Unduh Aplikasi dan Belanja Sekarang!.</a>

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ReadLoud                    
your_link                                 : https://github.com/readloud
your_city                                 : West Java | Indonesia                     
email_address                             : readloud7@gmail.com
facebook_username                         : readloud7
instagram_username                        : readloud7
twitter_username                          : readloud7
github_username                           : readloud7
youtube_username                          : UCfcbjJYlovhgxjyHhYtA3-



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : HEDOD OFFICIAL STORE | LAZADA ID
    description                           : Situs Belanja Online Fashion & Gaya Hidup. Kunjungi Toko Kami di <a href="https://www.lazada.co.id/hedod" alt="Hedod Official Store" target="_blank">Lazada</a>
    fontawesome_icon_name                 : magic
    
  - title                                 : VOUCHER 30K PENGGUNA BARU
    description                           : Dapatkan hadiah spesial khusus untuk kamu yang baru saja menginstal aplikasi Lazada. Ada voucher Rp. 30,000 untuk pembelian pertama Anda.
    fontawesome_icon_name                 : mobile

  - title                                 : CASHBACK SETIAP HARI
    description                           : Cashback harian hingga Rp. 35,000. Dapatkan koin setiap kali Anda mengunjungi aplikasi Lazada untuk ditukar dengan voucher belanja. Beli lebih banyak, lebih hemat!
    fontawesome_icon_name                 : play-circle

  - title                                 : MEREK RESMI & EKSKLUSIF DI LAZMALL
    description                           : Berbelanja dengan aman dan nyaman berkat jaminan 100% produk original dari merk favorit Anda dengan keunggulan produk 100% original, 15 hari pengembalian dan 1 hari pengiriman.
    fontawesome_icon_name                 : sync

  - title                                 : REKOMENDASI KHUSUS HANYA UNTUKMU
    description                           : Berbelanja semakin mudah dan nyaman dengan koleksi produk resmi, kategori dan brand yang telah dikurasi sesuai preferensi dan kebutuhan Anda, hadir langsung di halaman depan aplikasi Lazada.
    fontawesome_icon_name                 : adjust
  
  - title                                 : LIVESTREAMING
    description                           : Tonton Live Streaming dari LazLive dan dari seller di fitur feed dan jadilah yang pertama mengetahui produk terbaru secara langsung dan juga dapatkan voucher eksklusif selama live streaming.
    fontawesome_icon_name                 : star

  - title                                 : JAMINAN KEPUASAN BELANJA
    description                           : Aplikasi Lazada juga menampilkan review produk dari konsumen asli, penilaian penjual dan fitur chat langsung dengan penjual.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : PEMBAYARAN AMAN TERPERCAYA
    description                           : Bebaskan kekhawatiran Anda dengan metode pembayaran yang lengkap dan nyaman seperti COD (bayar di tempat), kredit Lazada, transfer bank, kartu kredit, bayar di minimarket dan aplikasi dompet virtual lainnya.
    fontawesome_icon_name                 : link

  - title                                 : VOUCHER DISKON & FLASH SALE SETIAP HARI
    description                           : Belanja lebih hemat dari sebelumnya dengan harga termurah setiap hari dengan voucher diskon, flash sale dan gratis ongkos kirim ke seluruh Indonesia.
    fontawesome_icon_name                 : circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : yellow                                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
